# Site Settings
lang: en
title: Imswarnil
title_1 : Im
title_2 : Swarnil
tagline: Clean, Simple, Minimalistic & Multipurpose Theme Made Using Bulma For Jekyll
logo_url: /assets/logo/imswarnil.png
email: your-email@domain.com
description: >
   Clean, Simple, Minimalistic & Multipurpose Theme Made Using Bulma For Jekyll
baseurl: ""
url: "https://jekyll.imswarnil.com"
permalink: pretty
#favicon: /path/to/favicon.png
gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5 
paginate_path: "/blog/page:num"

primary_color: "#E53935"
custom_theme: false

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: csrhymes

# _Adsense Ads
# config.yml
adsense: true
data-ad-client: ca-pub-1291242080282540

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass
  # load_paths: 
    # - node_modules

#google_analytics: UA-code-here
cookie_policy: /cookie-policy/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  videos:
    output: true
    layout: video
    thumbnail: https://placehold.co/600x400/E53935/FFF?text=Video+Image+Not+Found  # Default thumbnail for videos
    permalink: /:collection/:name
  products:
    output: true
    layout: product
    image: https://placehold.co/800x600/E53935/FFF  # Default thumbnail for videos
    sidebar: false
  projects:
    output: true
    permalink: /projects/:title


